name: Seller_App
description: A Mobile application for Seller
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter_switch: ^0.3.0
  intl: ^0.17.0
  cached_network_image: ^3.0.0
  flutter_secure_storage:
  http: ^0.13.1
  
  flutter:  
    sdk: flutter

  provider: ^5.0.0
  
  cupertino_icons: ^0.1.3
  introduction_screen: ^2.1.0
  circular_countdown_timer:
    

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
 
  assets:
    - assets/pizza.jpeg
    - assets/burger.jpeg
    - assets/Screen2.jpeg
    - assets/SellerLogo.jpeg
    - assets/chef.jpeg
    - assets/tottus.png
    - assets/Sodimac.png
    - assets/sodi.png
 
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  
